#!/bin/sh

. "$PM_FUNCTIONS"

command_exists hdparm || exit $NA

# Default values on battery
DRIVE_SPINDOWN_VALUE="${DRIVE_SPINDOWN_VALUE:-6}"
DRIVE_WRITE_CACHE="${DRIVE_WRITE_CACHE:-0}" 
DRIVE_POWER_MGMT="${DRIVE_POWER_MGMT:-1}"
DRIVE_ACOUSTIC_MGMT="${DRIVE_ACOUSTIC_MGMT:-254}"

# Default devices to operate on
DRIVE_LIST="/dev/[hs]d[a-z]"

help() {
cat <<EOF
--------
$0: Control hard drive spindown, write caching, 
    power management and acoustic management.

This hook has 4 tuneable parameters:
DRIVE_SPINDOWN_VALUE = time until a drive will spin down on battery
Defaults to 6, which will spin the drive down after 30 seconds of inactivity.

See the -S option on the hdparm manpage for more information.

DRIVE_WRITE_CACHE = Whether the drive caches writes on battery.
Defaults to 0 which means that the drive will not cache writes internally.

See the -W option on the hdparm man page for more information.

DRIVE_POWER_MGMT = Drive Advanced Power Management value on battery
Defaults to 1 for max power savings.

See the -B option on the hdparm man page

Drive acoustic management:
DRIVE_ACOUSTIC_MGMT = Drive Acoustic Management value on battery
Defaults to 128 for max quietness.

See the -M option on the hdparm man page. 

Drives to manage:
DRIVE_LIST = the list of hard drives to manage.
Defaults to "/dev/[hs]d[a-z]", which will manage up to the first 25 drives.

EOF
}

save_defaults() {
    for param in '-W' '-B' '-M'; do
        state_exists "${0##*/}-${1##*/}$param" && continue
        hdparm $param $1 |grep '=' |(read cmd eq val rest;
            savestate "${0##*/}-${1##*/}$param" "$val")
    done
}

read_defaults() {
    for param in '-W' '-B' '-M'; do
        state_exists "${0##*/}-${1##*/}$param" || continue
        case $param in
            '-W') DRIVE_WRITE_CACHE=$(restorestate "${0##*/}-${1##*/}$param");;
            '-B') DRIVE_POWER_MGMT=$(restorestate "${0##*/}-${1##*/}$param");;
            '-M') DRIVE_ACOUSTIC_MGMT=$(restorestate "${0##*/}-${1##*/}$param");;
        esac
    done
    DRIVE_SPINDOWN_VALUE=0
}

harddrive_set() {
    for dev in $DRIVE_LIST; do
        "$1" "$dev"
	# disable write caching, enable acoustic management
	printf "Toggling power management for %s..." "$dev"
	hdparm -W $DRIVE_WRITE_CACHE \
	    -S $DRIVE_SPINDOWN_VALUE \
	    -B $DRIVE_POWER_MGMT \
	    -M $DRIVE_ACOUSTIC_MGMT -F $dev >/dev/null 2>&1 \
	    && echo Done. || echo Failed.
    done
}

case $1 in
    true) harddrive_set save_defaults ;;
    false) harddrive_set read_defaults ;;
    help) help;;
    *) exit $NA ;;
esac

exit 0
