#!/bin/sh

. ${PM_FUNCTIONS}

JOURNAL_COMMIT_TIME=${JOURNAL_COMMIT_TIME:-600}

help() {
    cat <<EOF
Journal commit time parameters:

JOURNAL_COMMIT_TIME = number of seconds between journal commits on battery.
Defaults to 600 (10 minutes).

We currently only handle EXT3 filesystems
EOF
}

# actually remount the file system
remount_fs()
{
	# $1 = filesystem to remount
	# $2 = mount option to change
	mount -o remount,$2 $1
}

# invoked on an ext3 file system
handle_ext3()
{
	# $1 = filesystem to remount
	# $2 = commit time
	remount_fs $1 "commit=${2}"
}

handle_ext4() { handle_ext3 "$@"; }

handle_filesystems()
{
	# $1 = new journal commit time in seconds
	while read DEV MOUNT FSTYPE REST; 
	do
		command_exists "handle_${FSTYPE}" || continue
		printf "Setting journal commit time for %s to %d..." \
		    "$MOUNT" "$1"
		"handle_${FSTYPE}" $MOUNT $1 && echo Done. || echo Failed.
	done < /proc/mounts
}

case $1 in
	true) handle_filesystems $JOURNAL_COMMIT_TIME ;;
	false) handle_filesystems 0 ;;
        help) help;;
	*) exit $NA ;;
esac

exit 0

